### ISSUE TITLE
Internet Explorer Error

### ISSUE THREAD

**Issue by danwatco** [dirkfabisch/mediator#12]
When visiting the blog in explorer, the main container doesn't work and the content is pushed to the edges of the windows and looks bad without any borders or padding.

Thanks

**Comment by dirkfabisch** [comment]
Hi,

could some one please test if the issue could be closed?

**Comment by audreywatters** [comment]
I looked at my site (which uses Mediator) using IE yesterday, and the problem still exists.

**Comment by kmiya** [comment]
I found out that my pull requests (#20 and #21) were not sufficient.
If we change `<main class="content" role="main"> </main>` to `<div class="content" role="main"> </div>` on `index.html`, the main container works correctly on IE11.
But I'm not sure that this change is the best solution of this problem.

**Comment by dirkfabisch** [comment]
Please check the latest commit. I think I found a fix for the behavior in IE. See also: [HTML5 MAIN ELEMENT TAG NOT WORKING IN IE11](http://roger.steneteg.org/657/html5-main-element-tag-not-working-in-ie11/)

**Comment by kmiya** [comment]
Looks good to me on IE11. The container works correctly.

**Comment by amussey** [comment]
Just to confirm, this appears to fix the template as far back as IE9.  Thanks a bunch!
