### ISSUE TITLE
Jekyll Bootstrap

### ISSUE THREAD

**Issue by matheusrocha89** [dirkfabisch/mediator#24]
Hi @dirkfabisch , I am thinking on adapt your theme to easy install with jekyll bootstrap, I already did this with [lanyon theme](https://github.com/matheusrocha89/lanyon-jekyll-bootstrap), so I think I will try to do this with yours if you allow of course. What do you think about?

**Comment by dirkfabisch** [comment]
Hi @matheusrocha89, why not? I'm happy if you do this. Please credit my original work.

**Comment by matheusrocha89** [comment]
@dirkfabisch , Great, so I will do it this week, I will give the credits for your original work, for sure :) Later I will give you the repo url
