### ISSUE TITLE
Facebook title doesn't show

### ISSUE THREAD

**Issue by danilofreire** [dirkfabisch/mediator#27]
Hello Dirk!

First of all, congratulations for your template, I find it amazing. I'm having some issued with it, though. I've been trying to fix Facebook's sharing button, the one that appears on the bottom of every page. When I try to share a page with it, it doesn't show the title of the post, nor the blog description. I have no idea what's wrong. 

My blog repository [can be seen here](https://github.com/danilofreire/danilofreire.github.io). 

Thanks!

**Comment by usbsnowcrash** [comment]
I think facebook relies on opengraph tags being on the page.  I have a PR #46 which shows how I did this.

**Comment by danilofreire** [comment]
Thanks a lot for your reply, I'll take a look at your code :)

**Comment by teotwaki** [comment]
@danilofreire Can this be closed now?

**Comment by danilofreire** [comment]
Yes, sorry for not writing that earlier. Feel free to close the issue. Thanks again for your comments.

**Comment by teotwaki** [comment]
@dirkfabisch As per the previous comment, feel free to close this issue.
