### ISSUE TITLE
Post Images on mobile

### ISSUE THREAD

**Issue by yanivefraim** [dirkfabisch/mediator#38]
There is a problem with post images on mobile. If I want to use background image with real data, the image is cropped (see screenshots from example blog)

[mobile](http://prntscr.com/7bu4jq)
[desktop](http://prntscr.com/7bu4pt)

You can see that image content is different between those two...

**Comment by dirkfabisch** [comment]
Sorry, but I don't see the issue. Could you please describe it in more detail.

**Comment by yanivefraim** [comment]
Yes, I will try to add images from my blog (I already fixed it locally so I'll have to try and reproduce)

**Comment by dunphyben** [comment]
@yanivefraim I was also unhappy with how the banners looked on mobile. So I added a bit of responsive code to it. I laid out my solution on [issue #50](https://github.com/dirkfabisch/mediator/issues/50)

**Comment by dirkfabisch** [comment]
I integrated the solution from @dunphyben in the master branch in pull request #50.
