### ISSUE TITLE
Updating the Gemfile to reflect the changes in #42

### ISSUE THREAD

**Issue by sameera207** [dirkfabisch/mediator#43]
Since now we are using `Gemfile`, `README.md` should be updated to reflect the same

**Comment by usbsnowcrash** [comment]
I have a PR to do just this #45

**Comment by dirkfabisch** [comment]
Could I close this issue? It seems #45 fixed it :-)

**Comment by sameera207** [comment]
@dirkfabisch , @usbsnowcrash , sorry for the late reply, yeah you can close this :smile:
