### ISSUE TITLE
Favicon icon broken

### ISSUE THREAD

**Issue by TheAlbatross279** [dirkfabisch/mediator#54]
I forked your repo, but ended up copying it to my own. I noticed that the favicon didn't work when I added a .ico file to the assets/images/ dir.

I think I fixed it by changing the line in _includes/head.html:
```
  <link rel="shortcut icon" href="{{ "/assets/images/favicon.ico" | prepend: site.baseurl }}">
```

to including a '?':
```
  <link rel="shortcut icon" href="{{ "/assets/images/favicon.ico?" | prepend: site.baseurl }}">
```

**Comment by dirkfabisch** [comment]
Resolved with pull request #57
