### ISSUE TITLE
Fluid issue

### ISSUE THREAD

**Issue by yesimwilliam** [dirkfabisch/mediator#90]
Hi,

Was wondering if there is a way to fix the issue I have when running jekyll serve. Keep getting a lot of "Liquid Warning: Liquid syntax error"
Site still works but am concerned that it would break at some point. Am I missing something? 

![Screen Shot 2022-12-02 at 10 57 33 AM](https://user-images.githubusercontent.com/119123088/205356366-cdf2466b-1b03-41b2-8f15-0726bd2576c1.png)

Thank and love the theme!!

**Comment by yesimwilliam** [comment]
Hey just a suggestion, if you put this in your instructions, "Feel free to open issues if you run into trouble or have suggestions." You should respond to issues and questions in a timely manner. Yeah it's been 6 days for mine but there are some from 5 years ago that went I answered. Don't commit to such things if you can't or don't intend to follow through. If hell freezes over and you actually read this don't bother answering my question as I've moved on.

**Comment by dirkfabisch** [comment]
This is not my full time job and I work on this in my spare time. Please do not overinterpret a sentence. I never stated that I will integrate any pull request or that I'm able to fix issues. This is a best effort project, that was mainly initiated to fulfil my personal needs.
