### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by a3y3** [dirkfabisch/mediator#91]
Love this theme - any plans for adding support for dark mode? [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US) works great on this theme and it looks really great in dark mode!

**Comment by dirkfabisch** [comment]
I currently not using the theme anymore, therefore I don't plan to add any features.
